### ISSUE TITLE
Not Responding

### ISSUE THREAD

**Issue by Sp3cialneeds** [KDot227/Powershell-Token-Grabber#26]
anytime I click build exe it stops responding

**Comment by SonarServices** [comment]
Move-Item : Cannot find path 'C:\Users\x\Downloads\Powershell-Token-Grabber-main
(1)\Powershell-Token-Grabber-main\somalifuscator\Somalifuscator-main\main.exe' because it does not exist.
At C:\Users\x\Downloads\Powershell-Token-Grabber-main (1)\Powershell-Token-Grabber-main\builder.ps1:177 char:5
+     Move-Item -Path $somalifuscator_dir\main.exe -Destination $curren ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\x\...r-main\main.exe:String) [Move-Item], ItemNotFoundExce
   ption
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.MoveItemCommand

**Comment by KDot227** [comment]
> SonarServices

I'm not gonna help a kid who uploads "image loggers"

**Comment by SonarServices** [comment]
ok cunt im gonna fix it myself

**Comment by SonarServices** [comment]
😂  why would you create something new when all the shit is already open-sourced? its straight up just a waist of time, also being a skid means claiming "code" is your own when it belongs to someone else, which i dont. Also why did you release the grabber if you hate "skids" aka people who use grabbers from github so much?

**Comment by SonarServices** [comment]
yea ni it was just me being dumb

**Comment by KDot227** [comment]
> 😂 why would you create something new when all the shit is already open-sourced? its straight up just a waist of time, also being a skid means claiming "code" is your own when it belongs to someone else, which i dont. Also why did you release the grabber if you hate "skids" aka people who use grabbers from github so much?

1.) Not everything is open source lmao don't be slow + you can always make things that are better
2.) skid = script kiddie. You don't necessarily have to steal code to be called a skid
3.) You post dual hooked stuff to github so you already are dumb asf
4.) A lot of people who use this (example = @Chainski) actually contribute and make it better. I have nothing aginst people who use it.

**Comment by SonarServices** [comment]
1. I understand that not everything is open-source, but I personally choose not to use non open-source grabbers, and it's pretty obvious why I make that choice.
2. According to the definition I found on Urban Dictionary (here's the link: https://www.urbandictionary.com/define.php?term=skiddie), I do my due diligence before using any code from GitHub or other sources. I take the time to go through it and really understand it so that I can improve my own understanding.
3. It's actually kind of funny how open-source stuff can have both positive and negative aspects to it, right? It's a mix of emotions, really.
4. I want to make it clear that I never said that nobody contributes to open-source projects. It's true that I don't have a ton of experience in building and creating malware, which is why I don't try to make my own. However, I have taken the time to research things like reverse engineering programs/files and how antivirus software works. I even wrote a term paper on the subject and got a perfect score. But honestly, there's so much out there to learn, and my main focus is on web development rather than becoming a "hacker."

**Comment by KDot227** [comment]
> 1. I understand that not everything is open-source, but I personally choose not to use non open-source grabbers, and it's pretty obvious why I make that choice.
> 2. According to the definition I found on Urban Dictionary (here's the link: https://www.urbandictionary.com/define.php?term=skiddie), I do my due diligence before using any code from GitHub or other sources. I take the time to go through it and really understand it so that I can improve my own understanding.
> 3. It's actually kind of funny how open-source stuff can have both positive and negative aspects to it, right? It's a mix of emotions, really.
> 4. I want to make it clear that I never said that nobody contributes to open-source projects. It's true that I don't have a ton of experience in building and creating malware, which is why I don't try to make my own. However, I have taken the time to research things like reverse engineering programs/files and how antivirus software works. I even wrote a term paper on the subject and got a perfect score. But honestly, there's so much out there to learn, and my main focus is on web development rather than becoming a "hacker."

I think it's cool and all that your learning, but if that's the case, just get rid of the dual-hooked stuff. After that keep doing what your doing. For me, GitHub was the best way to learn to code and I still think it is, just don't post dual-hooked malware on it yk.

**Comment by SonarServices** [comment]
Alright, thank you for your understanding and I wish you a nice day.
